apiVersion: cloudshell.cloudtty.io/v1alpha1
kind: CloudShell
metadata:
  name: cloudshell-sample
spec:
  configmapName: "my-kubeconfig"
  runAsUser: "root"
  commandAction: "bash"
  ttl: 500
  once: false
  image: ghcr.io/cloudtty/cloudshell:v0.4.0
