apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudtty.controllerManager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: {{ include "cloudtty.controllerManager.fullname" . }}
    {{- if .Values.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.labels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: {{ include "cloudtty.controllerManager.fullname" . }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
      {{- include "common.tplvalues.render" (dict "value" .Values.apiserver.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels:
        control-plane: {{ include "cloudtty.controllerManager.fullname" . }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "cloudtty.controllerManager.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: {{ include "cloudtty.controllerManager.fullname" . }}
          image: {{ include "cloudtty.controllerManager.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - manager
          - --leader-elect-resource-namespace={{ .Release.Namespace }}
          - --v=2
          {{- with (include "cloudtty.operator.featureGates" .) }}
          - {{ . }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled}}
          livenessProbe: {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
            httpGet:
              path: /healthz
              port: 10357
          {{- end }}
          {{- if .Values.readinessProbe.enabled}}
          readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
            httpGet:
              path: /readyz
              port: 10357
          {{- end }}
          volumeMounts:
          - mountPath: /etc/cloudtty
            name: cloudtty-job-template
      volumes:
        - name: cloudtty-job-template
          configMap:
            name: {{ include "jobTemplate.config.fullname" . }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloudtty.controllerManager.fullname" . }}
      terminationGracePeriodSeconds: 10
