name: Test PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**

env:
  GO_VERSION: "1.20.4"
  GOLANGCI_VERSION: 'v1.52.2'

jobs:
  get_ref:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.result.outputs.ref }}
    steps:
      - name: Get Ref
        id: result
        run: |
          echo ref=${{ github.event.pull_request.head.sha }} >> $GITHUB_OUTPUT

